### ISSUE TITLE
Basic Authentication Insecure without HTTPS/TLS

### ISSUE THREAD

**Issue by twolffpiggott** [aws-samples/aws-mlflow-sagemaker-cdk#17]
Thanks for a great template for deploying MLflow on AWS and integrating it with SageMaker!

My main concern is that in this template, the UI is accessed with the basic auth credentials over an insecure connection (not HTTPS/TLS), and the credentials can be easily intercepted by a man in the middle attack.

In general, basic auth should only be used over a secure connection (HTTPS/TLS), see for example the [warning here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication).

Can this template be expanded to include certificate installation and management, and configuration of TLS for Nginx?

**Comment by pdifranc** [comment]
Hi Tim,

thank you for your interest in our sample :)

At this moment, we are not planning to extend the template to configure TLS for Nginx. In general, I would offload the whole TLS to other higher level services rather than to Nginx. However, you are absolutely right, basic auth over an unsecure channel over the internet is a security risk. However, thanks to how we architected the solution as a whole, this issue is partly mitigated. Let me try to explain:

Right now, when accessing the MLFlow UI, your request makes this trip (implemented by the `MLflowVpcStack` and `HttpGatewayStack` stacks):
your client -> (basic auth over the public internet over a secure channel (`https://<apigatewayidentifier>.execute-api.eu-west-1.amazonaws.com/`) -> Http Api Gateway -> (forward request with basic auth over a private connection over http thanks to a private link) -> Application Load Balancer -> (basic auth over a private connection over http) -> NGinx container (credentials checked, forward request) -> MLFlow container

As you can see, the only "unsecure" connections are between Http Api Gateway -> Application Load Balancer and Application Load Balancer -> Nginx container, both happening with private connection without going over the internet.

This means that your credentials could be potentially be hijacked only if a malicious user has access to the private network.

Different story is if you want to take the `MLFlowVpcStack` and open up the Application Load Balancer to the internet. If this is the case, then you could look into Route53 and Amazon Certificate Manager to implement the TLS and manage the whole certificate rotation for you.

I hope it makes sense to you.

I would be very interested to know how you are using this solution. Are you taking it as a whole, or only some pieces?

**Comment by pdifranc** [comment]
One possible extension of the template could consider whether the authentication should be done on Nginx at all, or it can be offloaded to the Http Api Gateway altogether, and implement any authentication mechanisms you prefer. From an architectural point of view, this would probably be the best approach. However this is something I have not explored yet, as there might be some challenges in accessing the MLFlow UI (the MLFlow API would work just fine).

**Comment by twolffpiggott** [comment]
Thanks for the quick response @pdifranc!

That makes sense, thanks, I was partly just opening this issue to see if I was missing something. I haven't instantiated anything from the template yet. I think if I had this would have been clear, but it's good to have a thread documenting it explicitly anyway.

I agree that the basic auth from client side going via the API Gateway over a secure channel effectively mitigates the risk I mentioned. The transmission of unencrypted creds over only a private connection shouldn't be a significant risk.

Agreed RE potentially offloading TLS to a higher-level service entirely. FWIW, what are the challenges you'd anticipate in accessing the UI if you handle authentication with the API Gateway?

At the moment I am just researching existing deployment and usage patterns combining SageMaker with MLflow. In general I'd definitely consider taking the solution as a whole, just might swap out components like Aurora -> Postgres for RDS. The notebooks are good for ad-hoc use, though I'd ultimately be aiming to automate relatively modular training pipelines that end in staging deployments.

**Comment by pdifranc** [comment]
Hi @twolffpiggott 

> Agreed RE potentially offloading TLS to a higher-level service entirely. FWIW, what are the challenges you'd anticipate in accessing the UI if you handle authentication with the API Gateway?

Well, the main challenges are the login form (should not be too hard) and then the session management/credentials the mlflow react component need to handle. I havent had the time to investigate more in depth how this could work without changes to the mlflow ui components.

> At the moment I am just researching existing deployment and usage patterns combining SageMaker with MLflow. In general I'd definitely consider taking the solution as a whole, just might swap out components like Aurora -> Postgres for RDS. The notebooks are good for ad-hoc use, though I'd ultimately be aiming to automate relatively modular training pipelines that end in staging deployments.

excellent! indeed the notebook is just an example about SageMaker / MLflow integration. Ultimately, you want to automate the whole workflow and there are several options for doing that, e.g., StepFunctions, SageMaker Pipelines (for the feature engineering and model building/training part at least), or combination of both.
